# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(default='nocover.jpg', max_length=255),
        ),
    ]
