# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authoID',
            new_name='id',
        ),
    ]
