# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='header',
            new_name='title',
        ),
    ]
