# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_auto_20171010_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_pic',
            field=models.CharField(default='writer.jpg', max_length=255),
        ),
    ]
