# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20171010_0320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookReview',
            new_name='Review',
        ),
        migrations.AddField(
            model_name='author',
            name='profile_pic',
            field=models.CharField(default='writer.jpg', max_length=255),
        ),
    ]
