# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 05:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20171030_1916'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0002_auto_20171105_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='previousorder',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together=set([('book', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='previousorder',
            unique_together=set([('book', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set([('book', 'user')]),
        ),
    ]
