# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_card',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
