# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_credit_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(default=None, max_length=50)),
                ('ccv', models.CharField(default=None, max_length=4)),
                ('exp_date', models.CharField(default=None, max_length=5)),
            ],
            options={
                'db_table': 'credit_cards',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='credit_card',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
