# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171011_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='credit_card_number',
            field=models.CharField(default=None, max_length=25, primary_key=True, serialize=False),
        ),
    ]
