# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171011_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='owner_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
