# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_creditcard_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_card',
            field=models.CharField(default='4200 0000 0000 0', max_length=50),
        ),
    ]
