# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_credit_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='ccv',
            new_name='cvv',
        ),
    ]
