# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171013_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='credit_card_number',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

    ]
